<a href="https://colab.research.google.com/github/Ashwithreddy12/upskillCampus/blob/main/Copy_of_Welcome_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Change this path to match your file location
filename = '/content/drive/MyDrive/test.py/2003.10.22.12.06.24'

# Load as numpy array
signal = np.loadtxt(filename)

print(signal[:10])


[[-0.022 -0.039 -0.183 -0.054 -0.105 -0.134 -0.129 -0.142]
 [-0.105 -0.017 -0.164 -0.183 -0.049  0.029 -0.115 -0.122]
 [-0.183 -0.098 -0.195 -0.125 -0.005 -0.007 -0.171 -0.071]
 [-0.178 -0.161 -0.159 -0.178 -0.1   -0.115 -0.112 -0.078]
 [-0.208 -0.129 -0.261 -0.098 -0.151 -0.205 -0.063 -0.066]
 [-0.232 -0.061 -0.281 -0.125  0.046 -0.088 -0.078 -0.078]
 [-0.112 -0.132 -0.181 -0.186 -0.132 -0.051 -0.132 -0.076]
 [-0.054 -0.107 -0.173 -0.134 -0.164  0.002 -0.146 -0.125]
 [-0.159 -0.032 -0.161 -0.181 -0.11  -0.044 -0.173 -0.137]
 [-0.225 -0.044 -0.09  -0.159 -0.1   -0.151 -0.139 -0.076]]


In [ ]:
import scipy.stats
from scipy.fftpack import fft

def extract_time_features(signal):
    return {
        'mean': np.mean(signal),
        'std': np.std(signal),
        'rms': np.sqrt(np.mean(signal**2)),
        'kurtosis': scipy.stats.kurtosis(signal),
        'skewness': scipy.stats.skew(signal),
        'peak_to_peak': np.ptp(signal)
    }

def extract_freq_features(signal):
    fft_vals = np.abs(fft(signal))
    fft_vals = fft_vals[:len(fft_vals)//2]
    spectral_entropy = -np.sum((fft_vals/np.sum(fft_vals)) * np.log2(fft_vals/np.sum(fft_vals) + 1e-12))
    return {
        'fft_mean': np.mean(fft_vals),
        'fft_std': np.std(fft_vals),
        'spectral_entropy': spectral_entropy
    }

# Load your file
signal = np.loadtxt('/content/drive/MyDrive/test.py/2003.10.22.12.06.24')

# Extract features
features = extract_time_features(signal)
features.update(extract_freq_features(signal))

print(features)


{'mean': np.float64(-0.09286718139648438), 'std': np.float64(0.08008967503344423), 'rms': np.float64(0.12263225280280156), 'kurtosis': array([1.06916276, 3.06588359, 0.20948596, 0.2922212 , 0.40543852,
       0.7770628 , 0.79024991, 1.80799019]), 'skewness': array([-0.02999276,  0.22011597, -0.09207326, -0.05318261,  0.03437157,
       -0.02222339,  0.04660896,  0.0082948 ]), 'peak_to_peak': np.float64(1.4849999999999999), 'fft_mean': np.float64(0.26689340628823616), 'fft_std': np.float64(0.22640794170386608), 'spectral_entropy': np.float64(15.89296879481312)}


In [ ]:
import pandas as pd

features['filename'] = '2003.10.22.12.06.24'
df = pd.DataFrame([features])
print(df)


       mean      std       rms  \
0 -0.092867  0.08009  0.122632   

                                            kurtosis  \
0  [1.0691627552877554, 3.0658835930955135, 0.209...   

                                            skewness  peak_to_peak  fft_mean  \
0  [-0.02999276480067818, 0.22011596507984527, -0...         1.485  0.266893   

    fft_std  spectral_entropy             filename  
0  0.226408         15.892969  2003.10.22.12.06.24  


In [ ]:
import os

def build_feature_dataframe(data_folder):
    features_list = []
    for fname in os.listdir(data_folder):
        path = os.path.join(data_folder, fname)
        if os.path.isfile(path):
            try:
                signal = np.loadtxt(path)
                features = extract_time_features(signal)
                features.update(extract_freq_features(signal))
                features['filename'] = fname
                features_list.append(features)
            except Exception as e:
                print(f"Error reading {fname}: {e}")
    return pd.DataFrame(features_list)

# Example usage
df_all = build_feature_dataframe('/content/drive/MyDrive/test.py')
print(df_all.head())


       mean      std       rms  \
0 -0.092867  0.08009  0.122632   

                                            kurtosis  \
0  [1.0691627552877554, 3.0658835930955135, 0.209...   

                                            skewness  peak_to_peak  fft_mean  \
0  [-0.02999276480067818, 0.22011596507984527, -0...         1.485  0.266893   

    fft_std  spectral_entropy             filename  
0  0.226408         15.892969  2003.10.22.12.06.24  


In [ ]:
import numpy as np
import pandas as pd
import scipy.stats
from scipy.fftpack import fft

# Load your single file
signal = np.loadtxt('/content/drive/MyDrive/test.py/2003.10.22.12.06.24')

# Extract features
features = {
    'mean': np.mean(signal),
    'std': np.std(signal),
    'rms': np.sqrt(np.mean(signal**2)),
    'kurtosis': scipy.stats.kurtosis(signal),
    'skewness': scipy.stats.skew(signal),
    'peak_to_peak': np.ptp(signal)
}

fft_vals = np.abs(fft(signal))
fft_vals = fft_vals[:len(fft_vals)//2]
spectral_entropy = -np.sum((fft_vals/np.sum(fft_vals)) * np.log2(fft_vals/np.sum(fft_vals) + 1e-12))
features['fft_mean'] = np.mean(fft_vals)
features['fft_std'] = np.std(fft_vals)
features['spectral_entropy'] = spectral_entropy

# Add filename
features['filename'] = '2003.10.22.12.06.24'

# Make DataFrame
df = pd.DataFrame([features])
print(df)


       mean      std       rms  \
0 -0.092867  0.08009  0.122632   

                                            kurtosis  \
0  [1.0691627552877554, 3.0658835930955135, 0.209...   

                                            skewness  peak_to_peak  fft_mean  \
0  [-0.02999276480067818, 0.22011596507984527, -0...         1.485  0.266893   

    fft_std  spectral_entropy             filename  
0  0.226408         15.892969  2003.10.22.12.06.24  
